name: Windows

on: [push, pull_request]

jobs:
  vs-win10:
    strategy:
      matrix:
        toolset: [Win32, x64]
        config: [Debug, Release]

    runs-on: windows-2019
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }} "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install -j2

    - name: DiligentToolsTest
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsTest\${{ matrix.config }}\DiligentToolsTest.exe"

    - name: DiligentToolsGPUTest D3D11
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsGPUTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsGPUTest\${{ matrix.config }}\DiligentToolsGPUTest.exe" --mode=d3d11_sw

    - name: DiligentToolsGPUTest D3D12
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsGPUTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsGPUTest\${{ matrix.config }}\DiligentToolsGPUTest.exe" --mode=d3d12_sw

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config == 'Release' }}
      with:
        name: DiligentTools-Windows10-${{ matrix.toolset }}-VS2019-${{ matrix.config }}
        path: |
          ${{runner.workspace}}\build\install\bin\DiligentTools
        retention-days: 90


  vs-win10-dev:
    strategy:
      matrix:
        toolset: [x64]
        config: [RelWithDebInfo]

    runs-on: windows-2019
    name: Win10 -> ${{ matrix.toolset }}, ${{ matrix.config }}, DEVELOPMENT

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }} "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON -DDILIGENT_DEVELOPMENT=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install -j2

    - name: DiligentToolsTest
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsTest\${{ matrix.config }}\DiligentToolsTest.exe"

    - name: DiligentToolsGPUTest D3D11
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsGPUTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsGPUTest\${{ matrix.config }}\DiligentToolsGPUTest.exe" --mode=d3d11_sw

    - name: DiligentToolsGPUTest D3D12
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsGPUTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsGPUTest\${{ matrix.config }}\DiligentToolsGPUTest.exe" --mode=d3d12_sw

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config != 'Debug' }}
      with:
        name: DiligentTools-Windows10-${{ matrix.toolset }}-VS2019-${{ matrix.config }}Dev
        path: |
          ${{runner.workspace}}\build\install\bin\DiligentTools
        retention-days: 90


  ninja-win10:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug]

    runs-on: windows-2019
    name: Win10-Ninja -> ${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup VS Development Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.toolset }}

    - name: Configure CMake
      if: success()
      env:
        CMAKE_GENERATOR: Ninja
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2


  vs-win8:
    strategy:
      matrix:
        toolset: [x64]
        config: [Release]

    runs-on: windows-2019
    name: Win10 -> Win8.1-${{ matrix.toolset }}, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "win" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }} "-DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_BUILD_TOOLS_INCLUDE_TEST=ON -DCMAKE_SYSTEM_VERSION=8.1"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} --target install -j2

    - name: DiligentToolsTest
      if: success()
      shell: bash
      run: |
        cd "${{runner.workspace}}\DiligentTools\DiligentTools\Tests\DiligentToolsTest\assets"
        "${{runner.workspace}}\build\DiligentTools\Tests\DiligentToolsTest\${{ matrix.config }}\DiligentToolsTest.exe"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() && matrix.config == 'Release' }}
      with:
        name: DiligentTools-Windows8-${{ matrix.toolset }}-VS2019-${{ matrix.config }}
        path: |
          ${{runner.workspace}}\build\install\bin\DiligentTools
        retention-days: 90
